-- SQL Dump of MinesAndProspects_1.2016.1..mdb
-- generated by MDB Viewer 2.2.6
-- optimized for PostgreSQL

SET NAMES 'UTF8';


CREATE TABLE "MRDSLookup" (
    "SequenceNumber" TEXT,
    "MRDSREC" TEXT,
    "SITENAME" TEXT,
    "DISTRICT" TEXT,
    "COUNTY" TEXT,
    "COUNTY2" TEXT,
    "SECQUAD" TEXT,
    "SECQUADSCL" TEXT,
    "UTMNORTH" TEXT,
    "UTMEAST" TEXT,
    "UTMZONE" TEXT,
    "COMMODIT" TEXT,
    "LAT" TEXT,
    "LON" TEXT,
    "TOWN" TEXT,
    "SECTION" TEXT,
    "RANGE" TEXT,
    "MrdsLookupKey" INTEGER
);

